# Generated by Django 2.2.11 on 2020-05-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200502_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_type',
            field=models.CharField(default='World', max_length=50),
        ),
    ]
