# Generated by Django 2.2.11 on 2020-05-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_blog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='head0',
        ),
    ]
